# Generated by Django 5.0.6 on 2024-07-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('food', 'Food'), ('fruits', 'Fruits'), ('electronics', 'Electronics'), ('fabric', 'Fabric'), ('homedecore', 'Home Decor'), ('wooditem', 'Wood Item')], max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
