# Generated by Django 5.0.6 on 2024-07-18 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_staff_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100, null=True)),
                ('buyer_number', models.IntegerField()),
                ('buyer_address', models.TextField(null=True)),
                ('buyer_email', models.EmailField(max_length=100)),
                ('buyer_pincode', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100, null=True)),
                ('seller_email', models.EmailField(max_length=100)),
                ('seller_address', models.TextField()),
                ('seller_number', models.IntegerField()),
                ('seller_quantity', models.IntegerField()),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buyer')),
            ],
        ),
    ]
