# Generated by Django 5.0.6 on 2024-07-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_buyer_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='staff_name',
            new_name='staff',
        ),
    ]
