# Generated by Django 5.0.6 on 2024-07-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_staff_name_order_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='staff',
            new_name='staffs',
        ),
    ]
