# Generated by Django 5.0.6 on 2024-07-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_staff_order_staffs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
